### PR TITLE
updated mixins to avoid deadlock

### PR DESCRIPTION
**Pull request by pietro-lopes**
This PR follows YUNG's API changes to avoid deadlocks on worldgen.

### CODE REVIEW

**Comment by Faboslav** [comment]
Thanks a lot! I will try to take a look at this this weekend and merge it.

**Comment by pietro-lopes** [comment]
Any progress?

**Comment by Faboslav** [comment]
Yeah, let me prepare a release with this merged.

**Comment by Faboslav** [comment]
Also is this only the 1.21.1 thing?

**Comment by pietro-lopes** [comment]
> Also is this only the 1.21.1 thing?

Looks like it is, I don't see any API change on YUNG's side.

**Pull request merged**
